# basic options
title: Online Portfolio
author: Sean Johnson
email: gy19saj@leeds.ac.uk
description:
---
title: About
---
 
github_username:  Seanj15
sidebar: Home

# Build settings
markdown: kramdown
theme: jekyll-theme-slate

