# basic options
title: Online Portfolio
author: Sean Johnson
email: gy19saj@leeds.ac.uk
description: An online portfolio of specific projects that I have completed using coding language. 
github_username:  Seanj15

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman

